# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('qoe-monitor-example-1', ['core','point-to-point','internet','qoe-monitor'])
    obj.source = 'qoe-monitor-example-1.cc'

    obj = bld.create_ns3_program('qoe-monitor-example-2', ['core','point-to-point','internet','network','applications','flow-monitor','qoe-monitor'])
    obj.source = 'qoe-monitor-example-2.cc'

    

